let clientPreview=false,previewOriginalSB=null,previewOriginalProfile=null,previewData=null,previewObserver=null,coachTab='business';
const BUSINESS_FIELDS={points:'Очки',wellness:'Wellness-оценки',meetings:'Встречи',talks:'Бизнес-разговоры',contacts:'Контакты',clients:'Новые клиенты',new_pc:'Новые ПК',new_np:'Новые НП',new_35:'Новые 35%',new_42:'Новые 42%',new_50:'Новые 50%'};
function isStaffWorkspace(){return staffConsultants.length>0&&!clientPreview}
function coachPlan(){return '<section class="card coach-tabs" role="tablist"><button data-coach-tab="business" role="tab" aria-selected="'+(coachTab==='business')+'">Бизнес</button><button data-coach-tab="result" role="tab" aria-selected="'+(coachTab==='result')+'">Результат</button></section><div id="coachPlanBody"></div>'}
function bindCoachPlan(){document.querySelectorAll('[data-coach-tab]').forEach(b=>b.onclick=()=>{coachTab=b.dataset.coachTab;bindCoachPlan()});document.querySelectorAll('[data-coach-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.coachTab===coachTab)));if(coachTab==='business')loadBusiness();else loadCoachResult()}
function businessPercent(goals,facts){const keys=Object.keys(BUSINESS_FIELDS).filter(k=>Number(goals[k])>0);return keys.length?Math.round(keys.reduce((s,k)=>s+Math.min(1,Number(facts[k]||0)/Number(goals[k])),0)/keys.length*100):null}
function businessTable(goals,facts){return '<div class="business-table"><table><thead><tr><th>Показатель</th><th>План</th><th>Факт</th><th>%</th></tr></thead><tbody>'+Object.entries(BUSINESS_FIELDS).map(([key,title])=>'<tr><th>'+title+'</th><td>'+ruNumber(goals[key]||0)+'</td><td>'+ruNumber(facts[key]||0)+'</td><td>'+(goals[key]>0?Math.round((facts[key]||0)/goals[key]*100)+'%':'—')+'</td></tr>').join('')+'</tbody></table></div>'}
function businessInputs(values){return '<div class="business-inputs">'+Object.entries(BUSINESS_FIELDS).map(([key,title])=>'<label>'+title+'<input name="'+key+'" type="number" min="0" max="10000000" step="'+(key==='points'?'0.1':'1')+'" inputmode="decimal" placeholder="0" value="'+escapeHtml(values[key]??'')+'"></label>').join('')+'</div>'}
function readBusinessForm(form){return Object.fromEntries(Object.keys(BUSINESS_FIELDS).map(k=>[k,Number(form.elements[k].value||0)]))}
async function loadBusiness(){
 const box=$('coachPlanBody');if(!box)return;box.innerHTML='<section class="card">Загружаем бизнес-план…</section>';
 try{const s=await checked(sb.rpc('ps_business_state'));if(!box.isConnected||coachTab!=='business')return;const w=s.weeks.find(w=>w.week_start===s.week),today=s.days.find(d=>d.entry_date===s.today)?.results||{},mp=businessPercent(s.month_targets,s.month_facts),wp=businessPercent(w.targets,w.facts);
 box.innerHTML='<section class="card"><div class="eyebrow">'+new Date(s.month+'T12:00:00').toLocaleDateString('ru-RU',{month:'long',year:'numeric'})+'</div><h2>Месячный план</h2><div class="business-score">'+(mp==null?'План не задан':mp+'%')+'</div>'+businessTable(s.month_targets,s.month_facts)+'<details><summary>Изменить план месяца</summary><form id="monthPlanForm">'+businessInputs(s.month_targets)+'<button class="btn primary">Сохранить план</button><p role="status"></p></form></details></section>'+
 '<section class="card"><h2>Факт за день</h2><form id="businessDayForm"><label>Дата<input id="businessDate" type="date" value="'+s.today+'" min="'+s.week+'" max="'+s.today+'" required></label><div id="businessDayInputs">'+businessInputs(today)+'</div><button class="btn primary">Сохранить результаты дня</button><p role="status"></p></form></section>'+
 '<section class="card"><h2>Текущая неделя</h2><p>'+dateLabel(s.week)+' — '+dateLabel(isoPlus(s.week,6))+'</p><div class="business-score">'+(wp==null?'План не задан':wp+'%')+'</div>'+businessTable(w.targets,w.facts)+'<p>Закрывается '+dateLabel(s.next_monday)+' в 00:00 по Якутску. После закрытия план и факт сохраняются в истории.</p><details><summary>План недели и анализ</summary><form id="weekPlanForm">'+businessInputs(w.targets)+'<label>Что получилось? Что улучшить?<textarea name="analysis" rows="4" maxlength="4000">'+escapeHtml(w.analysis||'')+'</textarea></label><button class="btn primary">Сохранить неделю</button><p role="status"></p></form></details></section>'+
 '<section class="card"><h2>История недель</h2>'+s.weeks.filter(w=>w.closed).map(w=>'<details class="week-history"><summary>'+dateLabel(w.week_start)+' — '+dateLabel(isoPlus(w.week_start,6))+' · '+(businessPercent(w.targets,w.facts)??0)+'%</summary>'+businessTable(w.targets,w.facts)+'<p class="pre-line">'+escapeHtml(w.analysis||'Анализ не добавлен')+'</p><span>Неделя закрыта</span></details>').join('')+(s.weeks.some(w=>w.closed)?'':'<p>Первая неделя появится здесь после закрытия.</p>')+'</section>';
 const bind=(id,kind,date)=>{const form=$(id);form.onsubmit=e=>{e.preventDefault();buttonAction(form.querySelector('button'),async()=>{await checked(sb.rpc('ps_save_business',{p_kind:kind,p_date:typeof date==='function'?date():date,p_values:readBusinessForm(form),p_analysis:form.elements.analysis?.value||''}));await loadBusiness()},form.querySelector('[role=status]'))}};
 bind('monthPlanForm','month',s.month);bind('businessDayForm','day',()=>$('businessDate').value);bind('weekPlanForm','week',s.week);
 $('businessDate').onchange=e=>{$('businessDayInputs').innerHTML=businessInputs(s.days.find(d=>d.entry_date===e.target.value)?.results||{})};
 }catch(e){journeyError(box,e,loadBusiness)}
}
function isoPlus(date,days){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function resultRouteHtml(s){const target=Number(assessment?.target_weight_kg)||null,start=s.startWeight,current=s.latestWeight,total=start!=null&&target!=null?Math.abs(start-target):0;const pct=total&&current!=null?Math.round(Math.max(0,Math.min(1,(target<start?start-current:current-start)/total))*100):start!=null&&current===target?100:0;return '<div class="plan-weight-route"><div><small>Старт</small><b>'+ruNumber(start)+' кг</b></div><div><small>Сейчас</small><b>'+ruNumber(current)+' кг</b></div><div><small>Цель</small><b>'+ruNumber(target)+' кг</b></div></div><div class="plan-progress-line"><i style="width:'+pct+'%"></i></div><p><b>'+pct+'% к цели</b> · Талия: '+ruNumber(s.latestWaist)+' см</p>'}
function resultGraph(rows,key,label,unit){const data=rows.filter(r=>r[key]!=null);if(!data.length)return '<p>Пока нет замеров '+label.toLowerCase()+'.</p>';const vals=data.map(r=>Number(r[key])),low=Math.min(...vals)-1,high=Math.max(...vals)+1;const x=i=>35+(data.length===1?0:i/(data.length-1)*280),y=v=>135-(v-low)/(high-low)*105;return '<h3>'+label+'</h3><svg class="result-chart" viewBox="0 0 350 165" role="img" aria-label="'+label+': '+ruNumber(vals[0])+' → '+ruNumber(vals.at(-1))+' '+unit+'"><line x1="35" y1="135" x2="325" y2="135" stroke="currentColor" opacity=".25"/><polyline fill="none" stroke="var(--green)" stroke-width="3" points="'+data.map((r,i)=>x(i)+','+y(r[key])).join(' ')+'"/>'+data.map((r,i)=>'<circle cx="'+x(i)+'" cy="'+y(r[key])+'" r="4" fill="var(--green)"><title>'+dateLabel(r.entry_date)+': '+ruNumber(r[key])+' '+unit+'</title></circle>').join('')+'<text x="5" y="22" fill="currentColor" font-size="12">'+ruNumber(high-1)+' '+unit+'</text><text x="35" y="158" fill="currentColor" font-size="11">'+dateLabel(data[0].entry_date)+'</text><text x="325" y="158" text-anchor="end" fill="currentColor" font-size="11">'+dateLabel(data.at(-1).entry_date)+'</text></svg>'}
async function loadCoachResult(){
 const box=$('coachPlanBody');if(!box)return;
 box.innerHTML='<section class="card"><h2>Мой результат</h2><div id="coachWeightRoute">Загружаем…</div><details><summary>Старт и цель</summary><form id="coachGoalForm"><label>Стартовый вес, кг<input name="start" type="number" min="25" max="400" step="0.1" value="'+escapeHtml(assessment?.starting_weight_kg??'')+'" required></label><label>Целевой вес, кг<input name="target" type="number" min="25" max="400" step="0.1" value="'+escapeHtml(assessment?.target_weight_kg??'')+'" required></label><label>Стартовая талия, см<input name="waist" type="number" min="30" max="250" step="0.1" value="'+escapeHtml(assessment?.waist_cm??'')+'"></label><button class="btn primary">Сохранить цель</button><p role="status"></p></form></details></section>'+pageProgress()+'<section class="card" id="coachGraphs">Загружаем графики…</section>';
 bindProgressPhotoActions();refreshCoachResult();
 $('coachGoalForm').onsubmit=e=>{e.preventDefault();const form=e.target;buttonAction(form.querySelector('button'),async()=>{await checked(sb.rpc('ps_save_coach_goal',{p_start:Number(form.elements.start.value),p_target:Number(form.elements.target.value),p_waist:form.elements.waist.value?Number(form.elements.waist.value):null}));assessment=await checked(sb.from('ps_assessments').select('*').eq('user_id',me.id).single());await refreshCoachResult();await loadProgressStats();form.querySelector('[role=status]').textContent='Цель сохранена ✓'},form.querySelector('[role=status]'))};
}
async function refreshCoachResult(){const route=$('coachWeightRoute'),graph=$('coachGraphs');try{const [s,rows]=await Promise.all([getProgressSummary(),checked(sb.from('ps_progress_entries').select('entry_date,weight_kg,waist_cm').eq('user_id',me.id).order('entry_date'))]);if(route?.isConnected)route.innerHTML=resultRouteHtml(s);if(graph?.isConnected)graph.innerHTML=resultGraph(rows,'weight_kg','Вес','кг')+resultGraph(rows,'waist_cm','Талия','см')+'<details><summary>Все замеры</summary><div class="business-table"><table><thead><tr><th>Дата</th><th>Вес</th><th>Талия</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+dateLabel(r.entry_date)+'</td><td>'+ruNumber(r.weight_kg)+'</td><td>'+ruNumber(r.waist_cm)+'</td></tr>').join('')+'</tbody></table></div></details>'}catch{if(route?.isConnected)route.textContent='Не удалось загрузить результат. Откройте вкладку ещё раз.'}}

// Preview uses the actual client rendering, with writes blocked before reaching Supabase.
function previewBlocked(){return {data:null,error:{message:'Предпросмотр: данные не сохраняются. Вернитесь в кабинет консультанта.'}}}
function previewQuery(q){return new Proxy(q,{get(t,k){if(['insert','update','upsert','delete'].includes(k))return ()=>previewQuery(Promise.resolve(previewBlocked()));const v=Reflect.get(t,k,t);if(k==='then')return v.bind(t);if(typeof v==='function')return (...a)=>{const next=v.apply(t,a);return next&&typeof next==='object'?previewQuery(next):next};return v}})}
function emptyPreviewQuery(){const q=new Proxy({},{get(t,k){if(k==='then')return (yes,no)=>Promise.resolve({data:[],error:null,count:0}).then(yes,no);return ()=>q}});return q}
function previewClient(real){return new Proxy(real,{get(t,k){if(k==='from')return (...a)=>a[0]==='ps_notifications'?emptyPreviewQuery():previewQuery(t.from(...a));if(k==='rpc')return async(name)=>{if(name==='ps_marathon_state')return {data:previewData};if(name==='ps_get_marathon_days')return {data:previewData.topics.map(d=>({...d,unlocked:d.day_number<=previewData.day,unlock_date:isoPlus(previewData.enrollment.start_date,d.day_number-1)}))};if(name==='ps_community_moderator')return {data:false};return previewBlocked()};if(k==='functions')return {invoke:async()=>previewBlocked()};if(k==='storage')return {from:bucket=>new Proxy(t.storage.from(bucket),{get(st,key){if(['upload','update','remove','move','copy'].includes(key))return async()=>previewBlocked();const v=st[key];return typeof v==='function'?v.bind(st):v}})};if(k==='auth')return new Proxy(t.auth,{get(a,key){if(['signOut','updateUser','signUp','signInWithPassword'].includes(key))return async()=>previewBlocked();const v=a[key];return typeof v==='function'?v.bind(a):v}});const v=t[k];return typeof v==='function'?v.bind(t):v}})}
async function enterClientPreview(){
 if(!staffConsultants.length||clientPreview)return;
 const button=$('clientPreviewNav');button.disabled=true;
 try{const topics=await checked(sb.from('ps_marathon_days').select('*').order('day_number'));const templates=await checked(sb.from('ps_marathon_task_templates').select('*').is('consultant_id',null).eq('active',true));const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Yakutsk',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 previewData={enrollment:{id:'preview',start_date:today,stars:0,duration_days:30},day:1,actual_day:1,percent:0,checks:[],topics,rewards:[10,25,50,75,100].map(n=>({id:'preview-'+n,milestone:n,gift:null})),tasks:Array.from({length:30},(_,i)=>templates.map(t=>({...t,day_number:i+1,enrollment_id:'preview',completed_at:null}))).flat()};
 stopCommunity();clientPreview=true;previewOriginalProfile=profile;profile={...profile,role:'client',consultant_id:staffConsultants[0].id};previewOriginalSB=sb;sb=previewClient(sb);staffNavigation();$('clientPreviewBar').classList.remove('hidden');
 previewObserver=new MutationObserver(disablePreviewWrites);previewObserver.observe($('content'),{childList:true,subtree:true});openPage('plan');disablePreviewWrites();
 }catch(e){alert('Не удалось открыть предпросмотр: '+e.message)}finally{button.disabled=false}
}
function disablePreviewWrites(){if(!clientPreview)return;document.querySelectorAll('#content input,#content textarea,#content form button,#content [data-claim],#content [data-read-notice],#saveMeasurementBtn,#beforePhotoBtn,#afterPhotoBtn,#makeCollageBtn,#profilePhotoBtn,#removeProfilePhotoBtn,#profileLogoutBtn,#communityPhotoBtn').forEach(el=>{el.disabled=true;el.title='Предпросмотр — без сохранения'});}
function exitClientPreview(){if(!clientPreview)return;stopCommunity();previewObserver?.disconnect();previewObserver=null;sb=previewOriginalSB;previewOriginalSB=null;profile=previewOriginalProfile;previewOriginalProfile=null;clientPreview=false;previewData=null;$('clientPreviewBar').classList.add('hidden');staffNavigation();openPage('coachPlan')}
