let incomingReferral=null,pendingCoachInvitation=null;
try{const url=new URL(location.href),token=new URLSearchParams(url.hash.slice(1)).get('invite');if(token&&/^[a-f0-9]{64}$/.test(token))sessionStorage.setItem('ps_coach_invite',token);pendingCoachInvitation=sessionStorage.getItem('ps_coach_invite');const ref=url.searchParams.get('ref');if(ref&&/^[A-Za-z0-9_-]{1,80}$/.test(ref))sessionStorage.setItem('ps_client_ref',ref);incomingReferral=sessionStorage.getItem('ps_client_ref')}catch{}
function showInvitationNotice(text){const el=$('invitationNotice');if(el){el.classList.remove('hidden');$('invitationNoticeText').textContent=text}}
function clearIncomingInvitation(){pendingCoachInvitation=null;incomingReferral=null;try{sessionStorage.removeItem('ps_coach_invite');sessionStorage.removeItem('ps_client_ref')}catch{}const url=new URL(location.href);url.hash='';url.searchParams.delete('ref');history.replaceState({},'',url);$('invitationNotice')?.classList.add('hidden');$('regConsultant').disabled=false;if(me)bootstrap();else loadConsultants()}
async function applyIncomingRegistration(consultants){
 if(pendingCoachInvitation){showInvitationNotice('Приглашение консультанта. Войдите по номеру, для которого оно создано, или зарегистрируйтесь с этим номером.');$('regConsultant').closest('label').hidden=true;return}
 $('regConsultant').closest('label').hidden=false;
 if(!incomingReferral)return;
 const c=consultants.find(c=>c.referral_code===incomingReferral);
 if(!c){showInvitationNotice('Эта ссылка консультанта недоступна. Выберите консультанта вручную.');$('regConsultant').disabled=false;return}
 $('regConsultant').value=c.id;$('regConsultant').disabled=true;showInvitationNotice('Регистрация клиента · ваш консультант: '+c.display_name);
 if(!me){$('loginBox').classList.add('hidden');$('registerBox').classList.remove('hidden')}
}
async function acceptPendingCoachInvitation(){if(!pendingCoachInvitation)return;await checked(sb.rpc('ps_accept_coach_invitation',{p_token:pendingCoachInvitation}));pendingCoachInvitation=null;try{sessionStorage.removeItem('ps_coach_invite')}catch{}const url=new URL(location.href);url.hash='';history.replaceState({},'',url);$('invitationNotice')?.classList.add('hidden')}
function pageMyQR(){return '<section class="card"><h2>QR для клиента</h2><div id="clientQR">Загружаем…</div></section><section class="card"><h2>Пригласить консультанта</h2><p>Одноразовая ссылка на 7 дней. Только для указанного номера.</p><form id="coachInviteForm"><label>Имя и фамилия<input name="inviteName" maxlength="100" required></label><label>Номер для входа<input name="invitePhone" type="tel" inputmode="tel" placeholder="+7 999 000-00-00" required></label><button class="btn primary">Создать приглашение</button><p role="status"></p></form><div id="newCoachInvite"></div></section><section class="card"><h2>Мои приглашения</h2><div id="coachInviteList">Загружаем…</div></section>'}
function appBaseUrl(){const url=new URL('./',location.href);url.search='';url.hash='';return url}
function qrMarkup(url,label,id){const qr=qrcode(0,'M');qr.addData(url,'Byte');qr.make();return '<div class="qr-card"><img id="'+id+'Image" src="'+qr.createDataURL(6,24)+'" alt="QR: '+escapeHtml(label)+'"><h3>'+escapeHtml(label)+'</h3><label>Ссылка<input id="'+id+'Link" readonly value="'+escapeHtml(url)+'"></label><button class="btn primary" id="'+id+'Share">Поделиться QR</button><button class="btn ghost" id="'+id+'Copy">Скопировать ссылку</button><a class="btn ghost app-link" href="'+qr.createDataURL(6,24)+'" download="protein-studio-qr.gif">Скачать QR</a><p id="'+id+'Status" role="status"></p></div>'}
function bindQR(url,label,id){const status=$(id+'Status');$(id+'Copy').onclick=async()=>{try{await navigator.clipboard.writeText(url);status.textContent='Ссылка скопирована ✓'}catch{$(id+'Link').select();status.textContent='Выделите и скопируйте ссылку.'}};$(id+'Share').onclick=async()=>{try{const img=$(id+'Image'),canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const file=blob?new File([blob],'protein-studio-qr.png',{type:'image/png'}):null;if(file&&navigator.canShare?.({files:[file]}))await navigator.share({title:label,text:label,url,files:[file]});else if(navigator.share)await navigator.share({title:label,text:label,url});else{$(id+'Copy').click();}}catch(e){if(e.name!=='AbortError')status.textContent='Можно скачать QR или скопировать ссылку.'}}}
async function bindMyQR(){
 const box=$('clientQR');try{const rows=await checked(sb.from('ps_consultants').select('id,display_name,referral_code').eq('user_id',me.id).eq('active',true));if(!box.isConnected)return;const c=rows[0];if(!c?.referral_code)throw Error('Не найдена персональная ссылка');const url=appBaseUrl();url.searchParams.set('ref',c.referral_code);box.innerHTML=qrMarkup(url.href,c.display_name,'clientQRCard');bindQR(url.href,'Регистрация в PROTEIN STUDIO · '+c.display_name,'clientQRCard')}catch(e){if(box.isConnected)box.textContent=e.message}
 const form=$('coachInviteForm');if(form)form.onsubmit=e=>{e.preventDefault();buttonAction(form.querySelector('button'),async()=>{const r=await checked(sb.rpc('ps_create_coach_invitation',{p_name:form.elements.inviteName.value.trim(),p_phone:normalizePhone(form.elements.invitePhone.value),p_target:null}));if(!form.isConnected)return;const url=appBaseUrl();url.hash='invite='+r.token;$('newCoachInvite').innerHTML='<p>Действует до '+dateLabel(r.expires_at)+'. Сохраните ссылку: повторно её текст не показывается.</p>'+qrMarkup(url.href,'Приглашение: '+form.elements.inviteName.value,'inviteQRCard');bindQR(url.href,'Приглашение консультанта PROTEIN STUDIO','inviteQRCard');loadCoachInvitations()},form.querySelector('[role=status]'))};loadCoachInvitations();
}
async function loadCoachInvitations(){const box=$('coachInviteList');if(!box)return;try{const rows=await checked(sb.rpc('ps_my_coach_invitations'));if(!box.isConnected)return;box.innerHTML=rows.length?rows.map(r=>'<article class="invite-row"><b>'+escapeHtml(r.name)+'</b><p>'+escapeHtml(r.phone)+'</p><p>'+(r.used_at?'Принято ✓':r.revoked_at?'Отозвано':new Date(r.expires_at)<new Date()?'Срок истёк':'Действует до '+dateLabel(r.expires_at))+'</p>'+(!r.used_at&&!r.revoked_at&&new Date(r.expires_at)>new Date()?'<button class="btn ghost" data-revoke-invite="'+r.id+'">Отозвать приглашение</button>':'')+'</article>').join(''):'<p>Приглашений пока нет.</p>';box.querySelectorAll('[data-revoke-invite]').forEach(b=>b.onclick=()=>buttonAction(b,async()=>{await checked(sb.rpc('ps_revoke_coach_invitation',{p_id:b.dataset.revokeInvite}));await loadCoachInvitations()},box))}catch{if(box.isConnected)box.textContent='Не удалось загрузить приглашения.'}}
