let directState=null,requestedThread=null,appRoute='plan';
const chatPeople=new Map();
async function loadChatPeople(ids){if(clientPreview)return;const rows=await checked(sb.rpc('ps_chat_people',{p_ids:[...new Set(ids)]}));await Promise.allSettled((rows||[]).map(async p=>{let url=null;if(p.avatar_path)try{url=await signedMedia('ps-progress-photos',p.avatar_path)}catch{}chatPeople.set(p.id,{...p,url})}));}
function chatAvatar(id,name){const p=chatPeople.get(id);return p?.url?'<img class="chat-avatar" src="'+escapeHtml(p.url)+'" alt="'+escapeHtml(name||p.full_name)+'">':'<span class="chat-avatar">'+escapeHtml((name||p?.full_name||'?').trim().split(/\s+/).slice(0,2).map(v=>Array.from(v)[0]).join(''))+'</span>'}
function pageMessages(){return '<div id="directView"><section class="card">Загружаем…</section></div>'}
function stopDirect(){if(directState){clearInterval(directState.timer);if(directState.channel)sb.removeChannel(directState.channel);directState=null}}
async function openClientDialog(client=null){if(clientPreview)return;try{requestedThread=await checked(sb.rpc('ps_open_dialog',{p_client:client}));openPage('messages')}catch(e){alert(e.message)}}
async function bindMessages(){const box=$('directView');if(clientPreview){box.innerHTML='<section class="card">Личные сообщения доступны в рабочем кабинете.</section>';return}try{
 const threads=await checked(sb.from('ps_direct_threads').select('*').order('created_at',{ascending:false}));
 if(!box.isConnected)return;
 if(requestedThread){const id=requestedThread;requestedThread=null;await showDirect(id);return}
 const savedThread=localStorage.getItem('ps_last_direct_thread_v56');if(savedThread){try{await showDirect(savedThread);return}catch{localStorage.removeItem('ps_last_direct_thread_v56')}}
 if(!isStaffWorkspace()){await openClientDialog();return}
 await loadChatPeople(threads.flatMap(t=>[t.client_id,t.coach_id]));
 const [messages,reads]=await Promise.all([checked(sb.from('ps_direct_messages').select('thread_id,sender_id,created_at').neq('sender_id',me.id).order('created_at',{ascending:false}).limit(1000)),checked(sb.from('ps_chat_reads').select('*').eq('user_id',me.id))]);
 if(!box.isConnected)return;
 box.innerHTML='<section class="card">'+(threads.length?threads.map(t=>{const person=chatPeople.get(t.client_id),n=messages.filter(m=>m.thread_id===t.id&&m.created_at>(reads.find(r=>r.channel===t.id)?.last_read_at||'')).length;return '<button class="dialog-row" data-thread="'+t.id+'">'+chatAvatar(t.client_id,person?.full_name)+'<b>'+escapeHtml(person?.full_name||'Клиент')+'</b>'+(n?'<span class="nav-badge">'+n+'</span>':'')+'</button>'}).join(''):'<p>Откройте карточку клиента и нажмите «Написать клиенту».</p>')+'</section>';
 box.querySelectorAll('[data-thread]').forEach(b=>b.onclick=()=>showDirect(b.dataset.thread));
}catch(e){journeyError(box,e,bindMessages)}}
async function showDirect(id){stopDirect();const box=$('directView');if(!box)return;try{localStorage.setItem('ps_last_direct_thread_v56',id)}catch{}
 const s=directState={id,rows:[],reply:null,busy:false,loading:false,limit:50,pending:null};
 box.innerHTML='<section class="community-chat"><button class="btn ghost" id="dialogBack">← Диалоги</button><div id="directLog" class="community-log"><button class="btn ghost" id="directOlder">Ранее</button><div id="directMessages"></div></div><form id="directForm" class="community-composer"><div id="directReply"></div><textarea name="body" rows="2" maxlength="3000" placeholder="Сообщение…"></textarea><label>＋ Фото<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="btn primary">Отправить</button><p role="status"></p></form></section>';
 $('dialogBack').onclick=()=>{try{localStorage.removeItem('ps_last_direct_thread_v56')}catch{}stopDirect();bindMessages()};$('directOlder').onclick=()=>{s.limit+=50;loadDirect(s)};
 $('directForm').onsubmit=e=>{e.preventDefault();sendDirect(s,e.target)};
 s.channel=sb.channel('private-'+id).on('postgres_changes',{event:'INSERT',schema:'public',table:'ps_direct_messages',filter:'thread_id=eq.'+id},()=>loadDirect(s)).subscribe();s.timer=setInterval(()=>{if(!document.hidden)loadDirect(s)},12000);await loadDirect(s);
}
async function loadDirect(s){if(directState!==s||s.loading||!$('directMessages'))return;s.loading=true;try{
 const [rows,consents]=await Promise.all([checked(sb.from('ps_direct_messages').select('*').eq('thread_id',s.id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(s.limit)),checked(sb.from('ps_result_consents').select('*').eq('thread_id',s.id))]);
 await loadChatPeople(rows.map(m=>m.sender_id));const urls=new Map();await Promise.allSettled(rows.filter(m=>m.image_path).map(async m=>urls.set(m.id,await signedMedia('ps-direct',m.image_path))));
 if(directState!==s||!$('directMessages'))return;const log=$('directLog'),bottom=log.scrollHeight-log.scrollTop-log.clientHeight<100||!s.rows.length;s.rows=rows.reverse();
 $('directMessages').innerHTML=s.rows.map(m=>{const person=chatPeople.get(m.sender_id),parent=s.rows.find(r=>r.id===m.reply_to),c=consents.find(c=>c.id===m.consent_id);return '<article class="chat-message '+(m.sender_id===me.id?'chat-own':'')+'"><div class="chat-message-head">'+chatAvatar(m.sender_id,person?.full_name)+'<b>'+escapeHtml(person?.full_name||'Участник')+'</b><time>'+new Date(m.created_at).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})+'</time></div>'+(m.reply_to?'<div class="chat-quote">'+escapeHtml(parent?.body||'Фото / раннее сообщение')+'</div>':'')+'<p class="chat-body">'+escapeHtml(m.body)+'</p>'+(urls.get(m.id)?'<img class="chat-image" src="'+escapeHtml(urls.get(m.id))+'" alt="Фото">':'')+(c?consentMarkup(c):'')+'<button class="chat-text-button" data-direct-reply="'+m.id+'">Ответить</button></article>'}).join('')||'<p class="chat-empty">Начните разговор</p>';
 $('directOlder').hidden=rows.length<s.limit;
 $('directMessages').querySelectorAll('[data-direct-reply]').forEach(b=>b.onclick=()=>{s.reply=b.dataset.directReply;$('directReply').textContent='Ответ: '+(s.rows.find(m=>m.id===s.reply)?.body||'Фото');const cancel=document.createElement('button');cancel.type='button';cancel.textContent='×';cancel.onclick=()=>{s.reply=null;$('directReply').textContent=''};$('directReply').append(cancel)});
 $('directMessages').querySelectorAll('[data-consent-answer]').forEach(b=>b.onclick=()=>buttonAction(b,async()=>{await checked(sb.rpc('ps_answer_result_consent',{p_id:b.dataset.id,p_answer:b.dataset.consentAnswer}));await loadDirect(s)},$('directForm').querySelector('[role=status]')));
 if(bottom)log.scrollTop=log.scrollHeight;
 if(!document.hidden&&s.rows.length){await checked(sb.rpc('ps_mark_chat_read',{p_channel:s.id,p_until:s.rows.at(-1).created_at}));await checked(sb.from('ps_notifications').update({read_at:new Date().toISOString()}).eq('recipient_id',me.id).eq('route->>thread',s.id).lte('created_at',s.rows.at(-1).created_at));refreshBadges()}
}catch(e){const p=$('directForm')?.querySelector('[role=status]');if(p)p.textContent=e.message}finally{s.loading=false}}
function consentMarkup(c){const words={pending:'Ожидает ответа',granted:'Разрешение дано ✓',denied:'Использование не разрешено',revoked:'Разрешение отозвано'};return '<div class="consent-card"><b>Использование результата</b><p>'+escapeHtml(c.scope)+'</p><p>'+words[c.status]+'</p>'+(c.client_id===me.id?(c.status==='pending'?'<button type="button" class="btn primary" data-id="'+c.id+'" data-consent-answer="granted">Разрешить</button><button type="button" class="btn ghost" data-id="'+c.id+'" data-consent-answer="denied">Не разрешать</button>':c.status==='granted'?'<button type="button" class="btn ghost" data-id="'+c.id+'" data-consent-answer="revoked">Отозвать разрешение</button>':''):'')+'</div>'}
async function sendDirect(s,form){if(s.busy||clientPreview)return;const body=form.elements.body.value.trim(),file=form.elements.photo.files[0];if(!s.pending&&!body&&!file)return;s.busy=true;const btn=form.querySelector('button[type=submit],button.btn.primary');btn.disabled=true;const status=form.querySelector('[role=status]');try{
 if(!s.pending)s.pending={id:crypto.randomUUID(),body,reply:s.reply,path:null};const p=s.pending;
 if(file&&!p.path){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760)throw Error('Фото JPG, PNG или WEBP до 10 МБ');const path=me.id+'/'+s.id+'/'+p.id+'.'+file.type.split('/')[1];const r=await sb.storage.from('ps-direct').upload(path,file,{contentType:file.type});if(r.error&&!/duplicate|already exists/i.test(r.error.message))throw r.error;p.path=path;}
 await checked(sb.rpc('ps_send_direct',{p_thread:s.id,p_id:p.id,p_body:p.body,p_photo:p.path,p_reply:p.reply}));s.pending=null;s.reply=null;form.reset();$('directReply').textContent='';status.textContent='';await loadDirect(s);
}catch(e){status.textContent=e.message+' · нажмите отправить для повтора'}finally{s.busy=false;btn.disabled=false}}
async function refreshBadges(){if(!me||clientPreview)return;try{const c=await checked(sb.rpc('ps_unread_counts'));for(const [page,label] of Object.entries({consultants:'💼 Консультанты',community:'👥 Группа поддержки',messages:'💬 Личные сообщения',notifications:'🔔 Уведомления'})){const nav=document.querySelector('[data-page="'+page+'"]');if(nav)nav.innerHTML='<span>'+label+'</span>'+(c[page]||c[page==='community'?'community':page]?'<span class="nav-badge">'+Math.min(999,c[page])+'</span>':'')}}catch{}}
async function delivery(data){const r=await sb.functions.invoke('ps-delivery',{body:data});if(r.error)throw Error('Не удалось подключиться. Попробуйте ещё раз.');if(r.data?.error)throw Error(r.data.error);return r.data}
function pushMarkup(){return '<section class="card"><button class="btn primary" id="enablePush">Включить уведомления</button><button class="btn ghost" id="disablePush">Отключить на этом устройстве</button><p id="pushStatus" role="status"></p></section>'}
async function bindPush(){const btn=$('enablePush');if(!btn)return;const status=$('pushStatus');const supported='PushManager'in window&&'Notification'in window&&'serviceWorker'in navigator;
 const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);const installed=navigator.standalone===true||matchMedia('(display-mode: standalone)').matches;
 if(!supported||(ios&&!installed)){status.textContent='На iPhone установите приложение на главный экран через «Поделиться», затем откройте его оттуда.';btn.disabled=true;return}
 if(Notification.permission==='granted'){btn.textContent='Проверить подключение уведомлений'}
 btn.onclick=()=>buttonAction(btn,async()=>{if(clientPreview)return;const permission=await Notification.requestPermission();if(permission!=='granted'){status.textContent='Разрешите уведомления в настройках телефона.';return}const reg=await navigator.serviceWorker.ready;const key=await delivery({action:'key'});if(!key.publicKey)throw Error('Push пока не настроен');const bytes=Uint8Array.from(atob(key.publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await delivery({action:'subscribe',subscription:sub.toJSON()});status.textContent='Уведомления включены ✓'},status);
 $('disablePush').onclick=()=>buttonAction($('disablePush'),async()=>{const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(sub){await delivery({action:'unsubscribe',endpoint:sub.endpoint});await sub.unsubscribe()}status.textContent='Уведомления отключены на этом устройстве'},status);
}
async function routeNotice(route){if(clientPreview)return;const p=route?.page||'notifications';if(p==='messages'&&route.thread)requestedThread=route.thread;if(p==='consultants'&&route.thread)requestedStaffThread=route.thread;openPage(['consultants','messages','community','admin','achievements','notifications'].includes(p)?p:'notifications');if(p==='admin'&&route.client&&isStaffWorkspace()){await loadAdminClients(adminViewVersion);await loadAdminClientDetail(route.client,adminViewVersion)}}
function consumePushRoute(){try{const url=new URL(location.href),r=url.searchParams.get('notice');if(r){url.searchParams.delete('notice');history.replaceState({},'',url);routeNotice(JSON.parse(r))}}catch{}}
if('serviceWorker'in navigator)navigator.serviceWorker.addEventListener('message',e=>{if(e.data?.type==='PS_NOTICE'&&me)routeNotice(e.data.route)});

async function detachPushOnLogout(){if(clientPreview)return;if('serviceWorker'in navigator&&'PushManager'in window){try{const reg=await navigator.serviceWorker.getRegistration();const sub=await reg?.pushManager.getSubscription();if(sub){try{await delivery({action:'unsubscribe',endpoint:sub.endpoint})}finally{await sub.unsubscribe()}}}catch{}}stopDirect();stopStaffChat();chatPeople.clear()}
