function workoutLibraryHtml(){return '<section class="card"><div id="workoutLibrary">Загружаем…</div></section>'}
function youtubeId(value){try{const u=new URL(value);let id=u.hostname==='youtu.be'?u.pathname.slice(1):(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname)?u.searchParams.get('v')||u.pathname.split('/').filter(Boolean)[1]:null);return /^[\w-]{11}$/.test(id||'')?id:null}catch{return null}}
function youtubePlayer(w){const id=youtubeId(w.video_url);return id?'<iframe class="youtube-player" src="https://www.youtube-nocookie.com/embed/'+id+'?playsinline=1" title="'+escapeHtml(w.title)+'" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture; fullscreen" allowfullscreen loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe><details class="video-fallback"><summary>Видео не воспроизводится?</summary><a class="btn ghost app-link" href="https://www.youtube.com/watch?v='+id+'" target="_blank" rel="noopener">Открыть на YouTube</a></details>':'<p>Проверьте ссылку видео.</p>'}
function workoutEditorHtml(){return '<section class="card"><h2>Добавить тренировку</h2><form id="workoutEditor"><label>Название<input name="title" maxlength="160" required></label><div class="two-col"><label>Длительность, минут<input name="minutes" type="number" min="1" max="180" value="10" required></label><label>Уровень<select name="level"><option>Начальный</option><option>Средний</option><option>Продвинутый</option></select></label></div><label>Где<select name="place"><option>Дома</option><option>Зал</option><option>Везде</option></select></label><label>Описание<textarea name="description" rows="3" maxlength="2000"></textarea></label><label>Источник<select name="source"><option value="youtube">Официальное видео Herbalife на YouTube</option><option value="upload">Наше короткое видео</option></select></label><label id="workoutUrlLabel">Ссылка YouTube<input name="url" type="url" placeholder="https://www.youtube.com/watch?v=..."></label><label id="workoutVideoLabel" hidden>Видео до 50 МБ<input name="video" type="file" accept="video/mp4,video/quicktime,video/webm"></label><label>Обложка<input name="cover" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="btn primary">Сохранить тренировку</button><p role="status"></p></form></section>'}
async function uploadWorkoutMedia(file){if(!file||!['image/jpeg','image/png','image/webp','video/mp4','video/quicktime','video/webm'].includes(file.type)||file.size>52428800)throw Error('Фото или короткое видео должно быть до 50 МБ.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/quicktime':'mov','video/webm':'webm'}[file.type];const path=me.id+'/'+crypto.randomUUID()+'.'+ext;await checked(sb.storage.from('ps-workout-media').upload(path,file,{contentType:file.type}));return path}
async function loadWorkoutLibrary(){
 const box=$('workoutLibrary');if(!box)return;
 try{
 const staff=isStaffWorkspace();
 const rows=await checked(sb.from('ps_workouts').select('*').eq('active',true).order('created_at',{ascending:false}));
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Yakutsk'}).format(new Date());
 const logs=staff?[]:await checked(sb.from('ps_workout_logs').select('*').eq('user_id',me.id).eq('log_date',today));
 if(!box.isConnected)return;
 box.innerHTML=rows.length?'<div class="workout-library-grid">'+rows.map(w=>{const log=logs.find(l=>l.workout_id===w.id);return '<article class="video-workout"><div class="workout-cover" '+(w.cover_path?'data-cover="'+escapeHtml(w.cover_path)+'"':'')+'>▶</div><h3>'+escapeHtml(w.title)+'</h3><p>'+w.minutes+' мин · '+escapeHtml(w.level)+' · '+escapeHtml(w.place)+'</p><p>'+escapeHtml(w.description)+'</p>'+(w.source_type==='youtube'?youtubePlayer(w):'<video controls playsinline preload="none" data-video-path="'+escapeHtml(w.video_path)+'"></video>')+(staff?'<button class="btn ghost" data-hide-workout="'+w.id+'">Убрать из каталога</button>':'<form data-workout-id="'+w.id+'"><label>Добавить фото тренировки<input type="file" accept="image/jpeg,image/png,image/webp"></label><button class="btn primary">'+(log?'Выполнено ✓ · сохранить фото':'Выполнено ✅')+'</button><p role="status"></p></form>'+(log?.photo_path?'<img class="task-photo" data-task-photo="'+escapeHtml(log.photo_path)+'" alt="Фото тренировки">':''))+'</article>'}).join('')+'</div>':'<p>'+(staff?'Добавьте ссылку на официальное видео или загрузите своё.':'Консультант скоро добавит видео.')+'</p>';
 await Promise.allSettled([...box.querySelectorAll('[data-cover]')].map(async el=>{const url=await signedMedia('ps-workout-media',el.dataset.cover);if(el.isConnected){const img=document.createElement('img');img.src=url;img.alt='Обложка тренировки';el.replaceChildren(img)}}).concat([...box.querySelectorAll('[data-video-path]')].map(async el=>{el.src=await signedMedia('ps-workout-media',el.dataset.videoPath)})));
 if(!box.isConnected)return;
 box.querySelectorAll('[data-workout-id]').forEach(form=>bindWorkoutLog(form,form.dataset.workoutId));
 box.querySelectorAll('[data-hide-workout]').forEach(b=>b.onclick=()=>buttonAction(b,async()=>{const w=rows.find(w=>w.id===b.dataset.hideWorkout);await checked(sb.rpc('ps_save_workout',{p_id:w.id,p_consultant:w.consultant_id,p_title:w.title,p_minutes:w.minutes,p_level:w.level,p_place:w.place,p_description:w.description,p_source:w.source_type,p_url:w.video_url,p_video:w.video_path,p_cover:w.cover_path,p_active:false}));loadWorkoutLibrary()},box));
 hydratePhotos(box);
 const free=$('freeWorkoutForm');if(free){bindWorkoutLog(free,null);if(logs.some(l=>!l.workout_id))free.querySelector('button').textContent='Выполнено ✓ · сохранить фото';}
 }catch(e){journeyError(box,e,loadWorkoutLibrary)}
 const editor=$('workoutEditor');if(editor&&!editor.dataset.bound){editor.dataset.bound='1';editor.elements.source.onchange=()=>{const upload=editor.elements.source.value==='upload';$('workoutUrlLabel').hidden=upload;$('workoutVideoLabel').hidden=!upload;editor.elements.url.disabled=upload;editor.elements.url.required=!upload;editor.elements.video.disabled=!upload;editor.elements.video.required=upload};editor.elements.source.onchange();editor.onsubmit=e=>{e.preventDefault();buttonAction(editor.querySelector('button'),async()=>{const f=editor.elements,source=f.source.value;let video=null,cover=null,url=null;if(source==='upload')video=await uploadWorkoutMedia(f.video.files[0]);else{url=f.url.value.trim();if(!youtubeId(url))throw Error('Укажите ссылку на YouTube.')}if(f.cover.files[0])cover=await uploadWorkoutMedia(f.cover.files[0]);await checked(sb.rpc('ps_save_workout',{p_id:null,p_consultant:staffConsultants[0].id,p_title:f.title.value.trim(),p_minutes:Number(f.minutes.value),p_level:f.level.value,p_place:f.place.value,p_description:f.description.value.trim(),p_source:source,p_url:url,p_video:video,p_cover:cover}));editor.reset();editor.elements.source.onchange();editor.querySelector('[role=status]').textContent='Тренировка сохранена ✓';loadWorkoutLibrary()},editor.querySelector('[role=status]'))}};
}
function bindWorkoutLog(form,id){form.onsubmit=e=>{e.preventDefault();buttonAction(form.querySelector('button'),async()=>{const file=form.querySelector('input').files[0],path=file?await uploadJourneyPhoto(file):null;await checked(sb.rpc('ps_log_workout',{p_workout:id,p_photo:path}));if(form.isConnected)form.querySelector('[role=status]').textContent='Тренировка сохранена ✓';showNewReward(await getJourney());await loadWorkoutLibrary()},form.querySelector('[role=status]'))}}
function taskSettingsHtml(){return '<section class="card"><details><summary>Шаблон заданий</summary><p>Для новых марафонов.</p><div id="taskSettingsList">Загружаем…</div><form id="taskTemplateForm"><h3>Новое задание</h3><label>Название<input name="title" maxlength="160" required></label><label>Тип<select name="kind"><option value="check">Галочка</option><option value="food_photo">Фото</option><option value="steps">Шаги</option></select></label><label>Звёзды<input name="stars" type="number" min="0" max="10" value="1" required></label><label>Цель шагов<input name="target" type="number" min="0" max="100000" value="5000"></label><button class="btn ghost">Добавить задание</button><p role="status"></p></form></details></section>'}
async function loadTaskSettings(){const box=$('taskSettingsList');if(!box)return;try{const rows=await checked(sb.from('ps_marathon_task_templates').select('*').or('consultant_id.is.null,consultant_id.eq.'+staffConsultants[0].id));if(!box.isConnected)return;const merged=new Map();rows.filter(r=>!r.consultant_id).forEach(r=>merged.set(r.task_key,r));rows.filter(r=>r.consultant_id).forEach(r=>merged.set(r.task_key,r));box.innerHTML=[...merged.values()].map(t=>'<form data-template="'+t.task_key+'" class="template-row"><label>Задание<input name="title" value="'+escapeHtml(t.title)+'" maxlength="160" required></label><div class="two-col"><label>Звёзды<input name="stars" type="number" value="'+t.stars+'" min="0" max="10" required></label><label>Цель шагов<input name="target" type="number" value="'+t.target+'" min="0" max="100000" '+(t.kind==='steps'?'':'disabled')+'></label></div><label class="inline-check"><input name="active" type="checkbox" '+(t.active?'checked':'')+'> Включено</label><button class="btn ghost">Сохранить</button><p role="status"></p></form>').join('');box.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const t=merged.get(f.dataset.template);buttonAction(f.querySelector('button'),async()=>{await saveTemplate(f,t.task_key,t.kind,f.elements.active.checked);f.querySelector('[role=status]').textContent='Сохранено ✓'},f.querySelector('[role=status]'))});const form=$('taskTemplateForm');form.onsubmit=e=>{e.preventDefault();buttonAction(form.querySelector('button'),async()=>{await saveTemplate(form,'custom_'+crypto.randomUUID().replaceAll('-',''),form.elements.kind.value,true);form.reset();loadTaskSettings()},form.querySelector('[role=status]'))}}catch{if(box.isConnected)box.textContent='Не удалось загрузить настройки.'}}
async function saveTemplate(form,key,kind,active){return checked(sb.rpc('ps_save_task_template',{p_consultant:staffConsultants[0].id,p_key:key,p_title:form.elements.title.value.trim(),p_kind:kind,p_stars:Number(form.elements.stars.value),p_target:kind==='steps'?Number(form.elements.target.value):0,p_active:active}))}

